name: Release

on:
  workflow_dispatch:
    inputs:
      distro:
        description: 'ROS Distro'
        required: true
        default: 'galactic'
        type: choice
        options:
        - galactic
        # - humble

jobs:
  deploy-debian-stable:
    name: Release ${{ github.event.inputs.distro }}
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/greenroom-robotics/ros_builder:latest
      options: --user root
    steps:
      - name: Checkout the branch as per distro
        uses: actions/checkout@v3
        with:
          path: ${{ github.repository }}

      - name: Add apt and rosdep sources
        env:
          API_TOKEN_GITHUB: ${{ secrets.TEMP_API_TOKEN_GITHUB }}
        run: |
          curl -s https://$API_TOKEN_GITHUB@raw.githubusercontent.com/Greenroom-Robotics/rosdistro/main/scripts/setup-rosdep.sh | bash -s
          curl -s https://$API_TOKEN_GITHUB@raw.githubusercontent.com/Greenroom-Robotics/packages/main/scripts/setup-apt.sh | bash -s

      - name: Download SDK binaries from GHCR
        run: |
          curl -L https://github.com/oras-project/oras/releases/download/v0.2.1-alpha.1/oras_0.2.1-alpha.1_linux_amd64.tar.gz | sudo tar -xzv -C /usr/local/bin oras
          oras login -u $GITHUB_ACTOR -p ${{ secrets.GITHUB_TOKEN }} ghcr.io
          (cd ${{ github.repository }}/arena_sdk_vendor; oras pull ghcr.io/greenroom-robotics/arenasdk:v0.1.59_amd64 -a)

      - name: Build Debian packages
        uses: Greenroom-Robotics/ros2-build-debian-action@bloom-mods
        with:
          ros2-distro: ${{ github.event.inputs.distro }}
          bloom-generate-extra-args: --ignore-shlibs-missing-info
          token: ${{ secrets.TEMP_API_TOKEN_GITHUB }}
          overlay-index: https://raw.githubusercontent.com/Greenroom-Robotics/rosdistro/main/overlay.yaml

      - name: Create a release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.event.inputs.distro }}-release
          files: |
            package/*.deb
            package/*.ddeb
          generate_release_notes: true

      - name: Push .deb to Greenroom Packages
        uses: Greenroom-Robotics/copy_file_to_another_repo_action@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.TEMP_API_TOKEN_GITHUB }}
        with:
          source_file: package/*.deb
          destination_repo: 'Greenroom-Robotics/packages'
          destination_folder: 'debian'
          user_email: 'ci@greenroomrobotics.com'
          user_name: 'Github CI'
          commit_message: 'feat: add debian package: https://github.com/${{ github.repository }}/commit/${{ github.sha }}'
